#
# Autogenerated by Thrift Compiler (0.14.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module Serialization
  class SimpleStruct; end

  class CollectionStruct; end

  class NestedStruct; end

  class ComplexStruct; end

  class SimpleStruct
    include ::Thrift::Struct, ::Thrift::Struct_Union
    INTEGER = 1
    DECIMAL = 2
    TEXT = 3

    FIELDS = {
      INTEGER => {:type => ::Thrift::Types::I32, :name => 'integer'},
      DECIMAL => {:type => ::Thrift::Types::DOUBLE, :name => 'decimal'},
      TEXT => {:type => ::Thrift::Types::STRING, :name => 'text'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class CollectionStruct
    include ::Thrift::Struct, ::Thrift::Struct_Union
    NUMBERS = 1
    DECIMALS = 2

    FIELDS = {
      NUMBERS => {:type => ::Thrift::Types::LIST, :name => 'numbers', :element => {:type => ::Thrift::Types::I64}},
      DECIMALS => {:type => ::Thrift::Types::SET, :name => 'decimals', :element => {:type => ::Thrift::Types::DOUBLE}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class NestedStruct
    include ::Thrift::Struct, ::Thrift::Struct_Union
    TEXTLIST = 1
    INTEGERTODOUBLE = 2

    FIELDS = {
      TEXTLIST => {:type => ::Thrift::Types::LIST, :name => 'textList', :element => {:type => ::Thrift::Types::STRING}},
      INTEGERTODOUBLE => {:type => ::Thrift::Types::MAP, :name => 'integerToDouble', :key => {:type => ::Thrift::Types::I32}, :value => {:type => ::Thrift::Types::DOUBLE}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class ComplexStruct
    include ::Thrift::Struct, ::Thrift::Struct_Union
    NESTEDSTRUCTLIST = 1
    INTEGERTONESTEDSTRUCT = 2

    FIELDS = {
      NESTEDSTRUCTLIST => {:type => ::Thrift::Types::LIST, :name => 'nestedStructList', :element => {:type => ::Thrift::Types::STRUCT, :class => ::Serialization::NestedStruct}},
      INTEGERTONESTEDSTRUCT => {:type => ::Thrift::Types::MAP, :name => 'integerToNestedStruct', :key => {:type => ::Thrift::Types::I32}, :value => {:type => ::Thrift::Types::STRUCT, :class => ::Serialization::NestedStruct}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end
