/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package serialization;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.1)", date = "2021-06-07")
public class CollectionStruct implements org.apache.thrift.TBase<CollectionStruct, CollectionStruct._Fields>, java.io.Serializable, Cloneable, Comparable<CollectionStruct> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CollectionStruct");

  private static final org.apache.thrift.protocol.TField NUMBERS_FIELD_DESC = new org.apache.thrift.protocol.TField("numbers", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField DECIMALS_FIELD_DESC = new org.apache.thrift.protocol.TField("decimals", org.apache.thrift.protocol.TType.SET, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CollectionStructStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CollectionStructTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.Long> numbers; // required
  public @org.apache.thrift.annotation.Nullable java.util.Set<java.lang.Double> decimals; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NUMBERS((short)1, "numbers"),
    DECIMALS((short)2, "decimals");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NUMBERS
          return NUMBERS;
        case 2: // DECIMALS
          return DECIMALS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NUMBERS, new org.apache.thrift.meta_data.FieldMetaData("numbers", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64))));
    tmpMap.put(_Fields.DECIMALS, new org.apache.thrift.meta_data.FieldMetaData("decimals", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CollectionStruct.class, metaDataMap);
  }

  public CollectionStruct() {
  }

  public CollectionStruct(
    java.util.List<java.lang.Long> numbers,
    java.util.Set<java.lang.Double> decimals)
  {
    this();
    this.numbers = numbers;
    this.decimals = decimals;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CollectionStruct(CollectionStruct other) {
    if (other.isSetNumbers()) {
      java.util.List<java.lang.Long> __this__numbers = new java.util.ArrayList<java.lang.Long>(other.numbers);
      this.numbers = __this__numbers;
    }
    if (other.isSetDecimals()) {
      java.util.Set<java.lang.Double> __this__decimals = new java.util.HashSet<java.lang.Double>(other.decimals);
      this.decimals = __this__decimals;
    }
  }

  public CollectionStruct deepCopy() {
    return new CollectionStruct(this);
  }

  @Override
  public void clear() {
    this.numbers = null;
    this.decimals = null;
  }

  public int getNumbersSize() {
    return (this.numbers == null) ? 0 : this.numbers.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.Long> getNumbersIterator() {
    return (this.numbers == null) ? null : this.numbers.iterator();
  }

  public void addToNumbers(long elem) {
    if (this.numbers == null) {
      this.numbers = new java.util.ArrayList<java.lang.Long>();
    }
    this.numbers.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.Long> getNumbers() {
    return this.numbers;
  }

  public CollectionStruct setNumbers(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.Long> numbers) {
    this.numbers = numbers;
    return this;
  }

  public void unsetNumbers() {
    this.numbers = null;
  }

  /** Returns true if field numbers is set (has been assigned a value) and false otherwise */
  public boolean isSetNumbers() {
    return this.numbers != null;
  }

  public void setNumbersIsSet(boolean value) {
    if (!value) {
      this.numbers = null;
    }
  }

  public int getDecimalsSize() {
    return (this.decimals == null) ? 0 : this.decimals.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.Double> getDecimalsIterator() {
    return (this.decimals == null) ? null : this.decimals.iterator();
  }

  public void addToDecimals(double elem) {
    if (this.decimals == null) {
      this.decimals = new java.util.HashSet<java.lang.Double>();
    }
    this.decimals.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Set<java.lang.Double> getDecimals() {
    return this.decimals;
  }

  public CollectionStruct setDecimals(@org.apache.thrift.annotation.Nullable java.util.Set<java.lang.Double> decimals) {
    this.decimals = decimals;
    return this;
  }

  public void unsetDecimals() {
    this.decimals = null;
  }

  /** Returns true if field decimals is set (has been assigned a value) and false otherwise */
  public boolean isSetDecimals() {
    return this.decimals != null;
  }

  public void setDecimalsIsSet(boolean value) {
    if (!value) {
      this.decimals = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case NUMBERS:
      if (value == null) {
        unsetNumbers();
      } else {
        setNumbers((java.util.List<java.lang.Long>)value);
      }
      break;

    case DECIMALS:
      if (value == null) {
        unsetDecimals();
      } else {
        setDecimals((java.util.Set<java.lang.Double>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case NUMBERS:
      return getNumbers();

    case DECIMALS:
      return getDecimals();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case NUMBERS:
      return isSetNumbers();
    case DECIMALS:
      return isSetDecimals();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof CollectionStruct)
      return this.equals((CollectionStruct)that);
    return false;
  }

  public boolean equals(CollectionStruct that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_numbers = true && this.isSetNumbers();
    boolean that_present_numbers = true && that.isSetNumbers();
    if (this_present_numbers || that_present_numbers) {
      if (!(this_present_numbers && that_present_numbers))
        return false;
      if (!this.numbers.equals(that.numbers))
        return false;
    }

    boolean this_present_decimals = true && this.isSetDecimals();
    boolean that_present_decimals = true && that.isSetDecimals();
    if (this_present_decimals || that_present_decimals) {
      if (!(this_present_decimals && that_present_decimals))
        return false;
      if (!this.decimals.equals(that.decimals))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetNumbers()) ? 131071 : 524287);
    if (isSetNumbers())
      hashCode = hashCode * 8191 + numbers.hashCode();

    hashCode = hashCode * 8191 + ((isSetDecimals()) ? 131071 : 524287);
    if (isSetDecimals())
      hashCode = hashCode * 8191 + decimals.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(CollectionStruct other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetNumbers(), other.isSetNumbers());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNumbers()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.numbers, other.numbers);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDecimals(), other.isSetDecimals());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDecimals()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.decimals, other.decimals);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("CollectionStruct(");
    boolean first = true;

    sb.append("numbers:");
    if (this.numbers == null) {
      sb.append("null");
    } else {
      sb.append(this.numbers);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("decimals:");
    if (this.decimals == null) {
      sb.append("null");
    } else {
      sb.append(this.decimals);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CollectionStructStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CollectionStructStandardScheme getScheme() {
      return new CollectionStructStandardScheme();
    }
  }

  private static class CollectionStructStandardScheme extends org.apache.thrift.scheme.StandardScheme<CollectionStruct> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CollectionStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NUMBERS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.numbers = new java.util.ArrayList<java.lang.Long>(_list0.size);
                long _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = iprot.readI64();
                  struct.numbers.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setNumbersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DECIMALS
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set3 = iprot.readSetBegin();
                struct.decimals = new java.util.HashSet<java.lang.Double>(2*_set3.size);
                double _elem4;
                for (int _i5 = 0; _i5 < _set3.size; ++_i5)
                {
                  _elem4 = iprot.readDouble();
                  struct.decimals.add(_elem4);
                }
                iprot.readSetEnd();
              }
              struct.setDecimalsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CollectionStruct struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.numbers != null) {
        oprot.writeFieldBegin(NUMBERS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, struct.numbers.size()));
          for (long _iter6 : struct.numbers)
          {
            oprot.writeI64(_iter6);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.decimals != null) {
        oprot.writeFieldBegin(DECIMALS_FIELD_DESC);
        {
          oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.DOUBLE, struct.decimals.size()));
          for (double _iter7 : struct.decimals)
          {
            oprot.writeDouble(_iter7);
          }
          oprot.writeSetEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CollectionStructTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CollectionStructTupleScheme getScheme() {
      return new CollectionStructTupleScheme();
    }
  }

  private static class CollectionStructTupleScheme extends org.apache.thrift.scheme.TupleScheme<CollectionStruct> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CollectionStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetNumbers()) {
        optionals.set(0);
      }
      if (struct.isSetDecimals()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetNumbers()) {
        {
          oprot.writeI32(struct.numbers.size());
          for (long _iter8 : struct.numbers)
          {
            oprot.writeI64(_iter8);
          }
        }
      }
      if (struct.isSetDecimals()) {
        {
          oprot.writeI32(struct.decimals.size());
          for (double _iter9 : struct.decimals)
          {
            oprot.writeDouble(_iter9);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CollectionStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list10 = iprot.readListBegin();
          struct.numbers = new java.util.ArrayList<java.lang.Long>(_list10.size);
          long _elem11;
          for (int _i12 = 0; _i12 < _list10.size; ++_i12)
          {
            _elem11 = iprot.readI64();
            struct.numbers.add(_elem11);
          }
        }
        struct.setNumbersIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TSet _set13 = iprot.readSetBegin();
          struct.decimals = new java.util.HashSet<java.lang.Double>(2*_set13.size);
          double _elem14;
          for (int _i15 = 0; _i15 < _set13.size; ++_i15)
          {
            _elem14 = iprot.readDouble();
            struct.decimals.add(_elem14);
          }
        }
        struct.setDecimalsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

