/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package serialization;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.1)", date = "2021-06-07")
public class SimpleStruct implements org.apache.thrift.TBase<SimpleStruct, SimpleStruct._Fields>, java.io.Serializable, Cloneable, Comparable<SimpleStruct> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SimpleStruct");

  private static final org.apache.thrift.protocol.TField INTEGER_FIELD_DESC = new org.apache.thrift.protocol.TField("integer", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField DECIMAL_FIELD_DESC = new org.apache.thrift.protocol.TField("decimal", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField TEXT_FIELD_DESC = new org.apache.thrift.protocol.TField("text", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SimpleStructStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SimpleStructTupleSchemeFactory();

  public int integer; // required
  public double decimal; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String text; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    INTEGER((short)1, "integer"),
    DECIMAL((short)2, "decimal"),
    TEXT((short)3, "text");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // INTEGER
          return INTEGER;
        case 2: // DECIMAL
          return DECIMAL;
        case 3: // TEXT
          return TEXT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __INTEGER_ISSET_ID = 0;
  private static final int __DECIMAL_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.INTEGER, new org.apache.thrift.meta_data.FieldMetaData("integer", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DECIMAL, new org.apache.thrift.meta_data.FieldMetaData("decimal", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.TEXT, new org.apache.thrift.meta_data.FieldMetaData("text", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SimpleStruct.class, metaDataMap);
  }

  public SimpleStruct() {
  }

  public SimpleStruct(
    int integer,
    double decimal,
    java.lang.String text)
  {
    this();
    this.integer = integer;
    setIntegerIsSet(true);
    this.decimal = decimal;
    setDecimalIsSet(true);
    this.text = text;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SimpleStruct(SimpleStruct other) {
    __isset_bitfield = other.__isset_bitfield;
    this.integer = other.integer;
    this.decimal = other.decimal;
    if (other.isSetText()) {
      this.text = other.text;
    }
  }

  public SimpleStruct deepCopy() {
    return new SimpleStruct(this);
  }

  @Override
  public void clear() {
    setIntegerIsSet(false);
    this.integer = 0;
    setDecimalIsSet(false);
    this.decimal = 0.0;
    this.text = null;
  }

  public int getInteger() {
    return this.integer;
  }

  public SimpleStruct setInteger(int integer) {
    this.integer = integer;
    setIntegerIsSet(true);
    return this;
  }

  public void unsetInteger() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __INTEGER_ISSET_ID);
  }

  /** Returns true if field integer is set (has been assigned a value) and false otherwise */
  public boolean isSetInteger() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __INTEGER_ISSET_ID);
  }

  public void setIntegerIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __INTEGER_ISSET_ID, value);
  }

  public double getDecimal() {
    return this.decimal;
  }

  public SimpleStruct setDecimal(double decimal) {
    this.decimal = decimal;
    setDecimalIsSet(true);
    return this;
  }

  public void unsetDecimal() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DECIMAL_ISSET_ID);
  }

  /** Returns true if field decimal is set (has been assigned a value) and false otherwise */
  public boolean isSetDecimal() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DECIMAL_ISSET_ID);
  }

  public void setDecimalIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DECIMAL_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getText() {
    return this.text;
  }

  public SimpleStruct setText(@org.apache.thrift.annotation.Nullable java.lang.String text) {
    this.text = text;
    return this;
  }

  public void unsetText() {
    this.text = null;
  }

  /** Returns true if field text is set (has been assigned a value) and false otherwise */
  public boolean isSetText() {
    return this.text != null;
  }

  public void setTextIsSet(boolean value) {
    if (!value) {
      this.text = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case INTEGER:
      if (value == null) {
        unsetInteger();
      } else {
        setInteger((java.lang.Integer)value);
      }
      break;

    case DECIMAL:
      if (value == null) {
        unsetDecimal();
      } else {
        setDecimal((java.lang.Double)value);
      }
      break;

    case TEXT:
      if (value == null) {
        unsetText();
      } else {
        setText((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case INTEGER:
      return getInteger();

    case DECIMAL:
      return getDecimal();

    case TEXT:
      return getText();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case INTEGER:
      return isSetInteger();
    case DECIMAL:
      return isSetDecimal();
    case TEXT:
      return isSetText();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof SimpleStruct)
      return this.equals((SimpleStruct)that);
    return false;
  }

  public boolean equals(SimpleStruct that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_integer = true;
    boolean that_present_integer = true;
    if (this_present_integer || that_present_integer) {
      if (!(this_present_integer && that_present_integer))
        return false;
      if (this.integer != that.integer)
        return false;
    }

    boolean this_present_decimal = true;
    boolean that_present_decimal = true;
    if (this_present_decimal || that_present_decimal) {
      if (!(this_present_decimal && that_present_decimal))
        return false;
      if (this.decimal != that.decimal)
        return false;
    }

    boolean this_present_text = true && this.isSetText();
    boolean that_present_text = true && that.isSetText();
    if (this_present_text || that_present_text) {
      if (!(this_present_text && that_present_text))
        return false;
      if (!this.text.equals(that.text))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + integer;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(decimal);

    hashCode = hashCode * 8191 + ((isSetText()) ? 131071 : 524287);
    if (isSetText())
      hashCode = hashCode * 8191 + text.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(SimpleStruct other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetInteger(), other.isSetInteger());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInteger()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.integer, other.integer);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDecimal(), other.isSetDecimal());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDecimal()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.decimal, other.decimal);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetText(), other.isSetText());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetText()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.text, other.text);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SimpleStruct(");
    boolean first = true;

    sb.append("integer:");
    sb.append(this.integer);
    first = false;
    if (!first) sb.append(", ");
    sb.append("decimal:");
    sb.append(this.decimal);
    first = false;
    if (!first) sb.append(", ");
    sb.append("text:");
    if (this.text == null) {
      sb.append("null");
    } else {
      sb.append(this.text);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SimpleStructStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SimpleStructStandardScheme getScheme() {
      return new SimpleStructStandardScheme();
    }
  }

  private static class SimpleStructStandardScheme extends org.apache.thrift.scheme.StandardScheme<SimpleStruct> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SimpleStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // INTEGER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.integer = iprot.readI32();
              struct.setIntegerIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DECIMAL
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.decimal = iprot.readDouble();
              struct.setDecimalIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TEXT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.text = iprot.readString();
              struct.setTextIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SimpleStruct struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(INTEGER_FIELD_DESC);
      oprot.writeI32(struct.integer);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(DECIMAL_FIELD_DESC);
      oprot.writeDouble(struct.decimal);
      oprot.writeFieldEnd();
      if (struct.text != null) {
        oprot.writeFieldBegin(TEXT_FIELD_DESC);
        oprot.writeString(struct.text);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SimpleStructTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SimpleStructTupleScheme getScheme() {
      return new SimpleStructTupleScheme();
    }
  }

  private static class SimpleStructTupleScheme extends org.apache.thrift.scheme.TupleScheme<SimpleStruct> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SimpleStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetInteger()) {
        optionals.set(0);
      }
      if (struct.isSetDecimal()) {
        optionals.set(1);
      }
      if (struct.isSetText()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetInteger()) {
        oprot.writeI32(struct.integer);
      }
      if (struct.isSetDecimal()) {
        oprot.writeDouble(struct.decimal);
      }
      if (struct.isSetText()) {
        oprot.writeString(struct.text);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SimpleStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.integer = iprot.readI32();
        struct.setIntegerIsSet(true);
      }
      if (incoming.get(1)) {
        struct.decimal = iprot.readDouble();
        struct.setDecimalIsSet(true);
      }
      if (incoming.get(2)) {
        struct.text = iprot.readString();
        struct.setTextIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

